### ISSUE TITLE
Should Provide Option for Graceful Handling of non-Finite Floats

### ISSUE THREAD

**Issue by Wardrop** [ruby/json#144]
Currently, the JSON library bombs out with an exception whenever it hits a non-finite float such as NaN or Infinite. It does provide an option to ignore these values as to include them in the JSON output as-is, but that generates invalid JSON which only moves the problem to the client. I'd like to suggest a new option be provided to allow one more control over how these non-finite (or otherwise invalid) values should be handled.

The option could be called something like "replace_nan" or something like that to keep it consistant with the "allow_nan" option. The possible values could be true, false or a proc. If false, the behaviour remains as it is currently. If true, the library replaces non-finite values with a relatively safe default, e.g. nil or 0. If a proc is given, the library should call the proc whenever a non-finite value is encountered, passing it the value itself. The return value of the proc is then used as the replacement value.

I don't think I need to justify this request with a use-case, but to give you an example in case you want one, I've just been called into work from holidays to fix an issue with an application I've written. It uses the EXIFR library to parse EXIF data from JPEG's and TIFF's. This typically generates NaN values which are serialised to the database. When this data is requested by the client, I need to perform a to_json on the serialised object which may include NaN's. Currently, it bombs out, and short of monkey-patching the #to_json method on the Float class, there's nothing I can do to work around this, except for some kind of elaborate recursive traversal of the object before it's jsoned, which is obviously a complex, fragile and slow solution.

**Comment by byroot** [comment]
This has been implemented a while ago through `allow_nan: true`
