### ISSUE TITLE
when generate json from ruby object, "ascii_only" not work, why???

### ISSUE THREAD

**Issue by jhjguxin** [ruby/json#178]
when I encode some hash to json on rails 4, I found the [method encode json is change](https://gist.github.com/jhjguxin/6240586).

so I generate json, by call `JSON.generate(object, :ascii_only => true)`, but when `object` is an class instance it not work.

more info please check [testjson](https://github.com/jhjguxin/testjson)

**Comment by byroot** [comment]
This is no longer relevant.
