### ISSUE TITLE
:space_before is broken

### ISSUE THREAD

**Issue by tenkai** [ruby/json#196]
puts JSON.generate( { "test" =>1, "omg" => "wtf"}, :indent => "  ", :object_nl => "\n", :space_before => " ", :space => " ")

the above line yields:
{
  "test": 1,
  "omg": "wtf"
}

when it is expected to yield: (the space before the : is not there)

{
  "test" : 1,
  "omg" : "wtf"
}

**Comment by byroot** [comment]
#225 has been merged.
