### ISSUE TITLE
Please update Unicode license blurb

### ISSUE THREAD

**Issue by zeha** [ruby/json#277]
Please update the unicode license blurb in ext/json/generator/generator.c (under the assumption that the file indeed comes from unicode.org and the new, free, Unicode.org license applies).

See https://bugs.ruby-lang.org/issues/11844 for more discussion/info.

**Comment by LukeShu** [comment]
This is causing problems for the Parabola GNU/Linux-libre distribution.  Our current solution is to remove the `generator.c` file and have it build the pure Ruby version of the gem; which is obviously sub-optimal.

**Comment by LukeShu** [comment]
The offending code is from the CVTUTF library, which was removed from unicode.org in 2009; perhaps some change to unicode.org/copyright.html affected it, but the license blurb in the file was never changed.

**Comment by bill-auger** [comment]
bump

a little love here?

this freedom bug against parabola is nearly four years old and nearly three years old against this repo with no acknowledgement

**Comment by bill-auger** [comment]
bump

5 years now - still no acknowledgement?

**Comment by voxik** [comment]
This still an issue. This time the UCD license was claimed nonfree and disallowed by Fedora:

https://gitlab.com/fedora/legal/fedora-license-data/-/merge_requests/88

**Comment by bill-auger** [comment]
welcome to the party fedrora :)

yeap, this makes 7 years now - yet, not a single acknowledgement from the maintainer - it looks like the only way this will be resolved, is if ruby drops this code-base entirely - unfortunately, the ruby folks were not eager to address it either
