### ISSUE TITLE
Error on invalid unicode / detecting it

### ISSUE THREAD

**Issue by tibbon** [ruby/json#329]
I'm trying to parse some JSON that comes from Twitter, but it contains invalid unicode. I don't control Twitter, so I kinda just have to roll with whatever they send in and handle it gracefully. Is there a way to more-gracefully handle that? 

```
[{"text":"Sounds good. Meeting Tuesday is fine. \ud83d\ude2d\ud83d..."}]
```

This raises several errors from the JSON parser. I have a failing test that you can see on the Twitter gem itself: https://github.com/sferik/twitter/pull/850

Also reference in this issue: https://github.com/sferik/twitter/issues/849

**Comment by tibbon** [comment]
I should note that even if I do `quirks_mode: true`, it fails in the same way. 

```
Twitter::Error: invalid escaped character at line 1, column 31984 [parse.c:259]
```

**Comment by rakslice** [comment]
In `json_string_unescape()`, in the case where a high surrogate is not followed by another Unicode character escape sequence, it is decoded as `?` **only if there are at least 6 more bytes in the JSON string representation**, otherwise `json_string_unescape()` gives an encoding error.  Either decoding as `?` is the right thing to do or giving an encoding error is the right thing to do, but it shouldn't depend on the number of unrelated bytes left.

**Comment by rakslice** [comment]
Is the encoding error in case intended to be there where there is a truncated code for handling a block from a stream or some other purpose I can't think of right now?

**Comment by tibbon** [comment]
Re: your last question, I don't know. Unsure of a what the right balance there is here for a solution. If there was a mode to just decode unknown things gracefully with a `?`, it would suit my personal needs, but I'm unsure if that fits in the larger project. 

Maybe I'll just make a fork and have it do that? Unsure. Since this is used on the Twitter Gem and this affects a lot of tweets, it feels important.

**Comment by tibbon** [comment]
I'm also going to just contact Twitter about their encoding strategy

**Comment by byroot** [comment]
I think supporting this sort of use case is way beyond the scope of a JSON parser, and is better handled by the various `encode` methods on String.
