### ISSUE TITLE
String#to_json behavior different for pure vs native ext

### ISSUE THREAD

**Issue by nirvdrum** [ruby/json#344]
The `String#to_json` method added when "json" is required has slightly different semantics for the pure vs native extension. In particular, a String with an invalid encoding throws an exception with the native exception but does not with the pure variant.

```
kjmenard@melchior /t/fog-json> ruby -ve 'require "json"; p "\x82\xAC\xEF".to_json'
ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-linux]
-e:1:in `to_json': source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
	from -e:1:in `<main>'

kjmenard@melchior /t/fog-json> ruby -ve 'require "json/pure"; p "\x82\xAC\xEF".to_json'
ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-linux]
"\"\x82\xAC\xEF\""
```

I think the pure version should raise an exception `unless string.valid_encoding?`.

**Comment by marcandre** [comment]
Confirmed with ruby 2.7.1p83
