### ISSUE TITLE
Update library to reflect the fact it is Ruby's default JSON implementation?

### ISSUE THREAD

**Issue by zverok** [ruby/json#348]
While trying to make small [docs update PR](https://github.com/flori/json/pull/347) I found out the next facts that probably should be addressed:

* The repo has no indication that it is **the** default Ruby's JSON implementation, it just states that "it is _an_ implementation" (therefore I falsely believed that upstream for stdlib `json` is `ruby/ruby` repo, and this one is just a pre-Ruby 2 standalonge gem);
* The `json` gem and `json` stdlib share some, but not all, code and docs, which lead to the weird effects:
  * the whole thing about two implementation (C and pure) has an effect on design and docs, but "pure" implementation is not imported into Ruby trunk, which, for example, renders [documentation](https://docs.ruby-lang.org/en/2.5.0/JSON.html) pieces like this: 
![image](https://user-images.githubusercontent.com/129656/37165461-590f9f04-2305-11e8-8700-84108f7be250.png)
  (`JSON::Pure::Generator` is not a thing in stdlib);
  * moreover, considering no need for two implementations, the library code and interface can be simplified significantly (no `.generator` and `.parser` attributes, no need to have a separate `Common` module and so on);
  * most of the detailed docs on gem usage and examples are in README, but not in `JSON` module's RDoc, and are not accessible from the standard library docs

Is it possible to somehow "freezing" the fact that `json` gem for future Ruby versions should only be available through stdlib, and simplify the library accordingly?

**Comment by byroot** [comment]
I don't quite know how to action this, so feel free to open PR so it's more concrete.

For the link with Ruby, now that the repo has moved I think it's more evident.

**Comment by zverok** [comment]
Yeah, the thing with confusing standard docs due to two generators is still relevant:
![image](https://github.com/user-attachments/assets/58660587-9b8f-4e14-b274-57ec428814c2)

...but since 2018 I came to understanding that it is not that simple. 
I’ll try to look into improving the approach to the documentation in upcoming months, as the gem now is in active maintenance!
