### ISSUE TITLE
DateTime and Time produce different output

### ISSUE THREAD

**Issue by Wardrop** [ruby/json#351]
I'm guessing this isn't the expected behaviour:

``` ruby
require 'date'
require 'json'
Time.now.to_json #=> "\"2018-03-14 16:51:50 +1000\"" 
DateTime.now.to_json #=> "\"2018-03-14T16:51:50+10:00\"" 
```

DateTime#to_json seems to produce the correct output (ISO 8601), where as Time#to_json does not.

**Comment by Wardrop** [comment]
Looking further into it, it seems this library is merely using #to_s on each object. DateTime happens to output a ISO 8601 compliant string, where as Time does not.

**Comment by byroot** [comment]
Yes.
