### ISSUE TITLE
symbolize_names is a confusing method name

### ISSUE THREAD

**Issue by CodingAnarchy** [ruby/json#370]
The `symbolize_names` option is confusing and out of sync with the rest of the Ruby standard library.  For instance, the `Hash` class uses `symbolize_keys` as a method.  It seems that "name" is only used in JSON documentation (where things are referred to as "name-value" pairs instead of "key-value" pairs).  This is, I believe, intended to indicate that the key has to be a string, but when dealing with Ruby parsing it is confusing to remember that only the JSON library has a different name.

Is there any way we can add an alias to the option as `symbolize_keys`?

**Comment by mick03131** [comment]
Ok

**Comment by esotericpig** [comment]
As a side note, YAML also calls it `symbolize_names`, so probably YAML (Psych) would also need to be updated.

```ruby
YAML.safe_load(data,symbolize_names: true)
```

So at the very least, JSON and YAML (for `symbolize_names`) are consistent with each other.

**Comment by byroot** [comment]
As noted this option was named this way to mirror YAML.

If someone open a PR to add `symbolize_keys` as an alias I'll merge it, but I don't think it's really that useful so I won't do it myself.
