### ISSUE TITLE
json/add/core isn't complete

### ISSUE THREAD

**Issue by na-sa-do** [ruby/json#382]
Several `json/add/*.rb` are not required by `json/add/core`. It should probably check its directory and require the contents automatically, to ensure this doesn't end up happening again if more are added.

Actually, why is it a separate module at all? Shouldn't it be implied by `require 'json'`?

**Comment by ViKomprenas** [comment]
Bump?

**Comment by byroot** [comment]
No plans to make much changes to `json/add`, it's been the source of many security vulnerabilites in the past and should be considered deprecated.
