### ISSUE TITLE
rubygems.org links are outdated

### ISSUE THREAD

**Issue by magneland** [ruby/json#411]
Hi!
I normally use rubygems.org to navigate to gems.
I noticed that from here:
https://rubygems.org/gems/json

The links to Homepage and Source Code both go to:
http://flori.github.io/json/

This is clearly outdated as the first paragraph reads:

> This is a implementation of the JSON specification according to RFC 4627. You can think of it as a low fat alternative to XML, if you want to store data to disk or transmit it over a network rather than use a verbose markup language.

While the link to Documentation go to:
http://flori.github.io/json/doc/index.html

Also this is very much outdated, as indicated by the footer:

> Last modified: 2012-09-14 17:53:45 +0200

Maybe the solution is just to point to the GitHub repo and delete the old websites?

**Comment by hsbt** [comment]
Fixed at https://github.com/flori/json/pull/508

**Comment by hsbt** [comment]
I don't have admin grant. So, I couldn't update github-pages with its configuration.

**Comment by olleolleolle** [comment]
> I don't have admin grant. So, I couldn't update github-pages with its configuration.

Perhaps _now_ this is possible?

**Comment by byroot** [comment]
I'm now admin, I'm trying to understand what is missing to solve this.

**Comment by olleolleolle** [comment]
This link is now updated, pointing to something good, which seems to be the GitHub pages output from this repo. Looks done!

![image](https://github.com/user-attachments/assets/c7ff73a3-40d0-426f-9bc5-f4ae7348f956)
