### ISSUE TITLE
Missing documentation for `object_class` and `array_class`

### ISSUE THREAD

**Issue by marcandre** [ruby/json#419]
It's unclear what methods `object_class` and `array_class` should respond_to. Is it only `.new` and `#[]=` / `.new` and `#<<` respectively? This should be documented.

Followup to #413

**Comment by byroot** [comment]
Digging into the C and Pure implementations:

  - `array_class` must respond to `#new` and return an object that responds to `#<<`.
  - `object_class` must respond to `#new` and return an object that responds to `#[]=`.

I'll try to update the documentation.
