### ISSUE TITLE
support not adding a newline for empty hashes when pretty_generating

### ISSUE THREAD

**Issue by fawaf** [ruby/json#437]
currently, `pretty_generate` will add a newline to the output if there is a hash or array that is empty:
```json
{
  "blah":"bar",
  "foo": {
  },
  "baz": [
  ]
}
```

this is to add an optional argument to not generate that newline. e.g.
```json
{
  "blah":"bar",
  "foo": {},
  "baz": []
}
```

**Comment by byroot** [comment]
I'm thinking this should just the the default to be honest.
