### ISSUE TITLE
IPAddr#to_json remove prefix address with CIDR

### ISSUE THREAD

**Issue by taketo1113** [ruby/json#503]
IPAddr#to_json removed the prefix address with IPAddr/CIDR value.
It unable to deserialize IPAddr/CIDR value.

### Expected behavior
```ruby
require 'date'
require 'json'

IPAddr.new('172.16.0.0/24').to_json #=> "\"172.16.0.0/24\""
```

### Actual behavior
```ruby
require 'ipaddr'
require 'json'

IPAddr.new('172.16.0.0/24').to_json #=> "\"172.16.0.0\""
```

### Related URL
- https://github.com/rails/rails/issues/46006

**Comment by byroot** [comment]
The JSON gem has no specific support for `IpAddr`. I suspect this is a change in `IpAddr#to_s` which is what JSON call when it doesn't know about a particular type.

**Comment by taketo1113** [comment]
Thanks to reply.

> The JSON gem has no specific support for IpAddr. 

I will create PR to add `IPAddr#to_json` method in ipaddr gem.
Becase I think the changing behavior of `IPAddr#to_s` has breaking compatibility.

see. https://github.com/rails/rails/pull/52365

**Comment by taketo1113** [comment]
cc: @byroot 
I have created PR to add `IPAddr#to_json/as_json` for ipaddr gem.
https://github.com/ruby/ipaddr/pull/77
