### ISSUE TITLE
JSON gem is slow parsing integers/floats when there's multiple threads executing at once (in Ractors)

### ISSUE THREAD

**Issue by luke-gru** [ruby/json#511]
See https://bugs.ruby-lang.org/issues/19288

I've opened this issue just to notify you guys.

**Comment by luke-gru** [comment]
I'm sorry for the noise, this issue is with Ractor#send and not with this json 😸

**Comment by luke-gru** [comment]
It looks like part of the issue is that interning all the object names is causing lots of VM locks, because the frozen strings are per-vm, not per ractor, so a VM lock is necessary to search or update the frozen string table.

**Comment by byroot** [comment]
Closing as I don't think this is actionable on this side, unless I'm missing something.

I see how interning strings would require a global vm lock, but assigning a string as a Hash key does attempt to intern the string anyway as far as I'm aware.

If there something you think we could do, I'll all ears, but in the meantime I'm trying to close non-actionable issues.
