### ISSUE TITLE
How to use both, pure and ext variant

### ISSUE THREAD

**Issue by mrckzgl** [ruby/json#523]
Hi,

(until fix for https://github.com/flori/json/issues/515 gets released,) we want to use the pure variant to pretty generate some of our json (where it is important to have correct formatting), however for everything else the ext variant is preferred, as it is faster.
Two problems arise with this:
1) I haven't figured out in the docs how to explicitly use a specific variant while both are loaded. There is only one global object JSON which exposes the pretty_generate function. JSON::Ext or JSON::Pure do not. So how to explicitly call json pure pretty_generate?
2) Whatever order I do the imports: `require "json/ext"` / `require "json/pure"`, in both cases `JSON::Generator` resolves to `JSON::Pure::Generator`. How to load both variants and let `JSON::Ext::Generator` be the default?

**Comment by byroot** [comment]
You can directly use `JSON::Pure::Generator::State.new(opts).generate`, and it will mostly work.

But it's not really fully supported, and I'm not sure it could, each implementation define a number of `to_json` methods on various core types, and that unfortunately is fully global. So it works as long as you never end up recursively calling one of these methods.
