### ISSUE TITLE
Compatibility with new ruby 3.3.0

### ISSUE THREAD

**Issue by sydverisk** [ruby/json#566]
Hi,

I'm seeking confirmation regarding the compatibility of the json gem version 2.7.1 (released December 05, 2023) with the recently released Ruby 3.3.0 (December 25, 2023).

While I reviewed the gem's documentation on RubyGems (https://rubygems.org/gems/json), it only specifies a minimum required Ruby version of 2.3. Unfortunately, I haven't found any explicit confirmation on compatibility with newer versions like 3.3.0.

Given your expertise in this area, could you offer any insights or leads on this matter? Any information you can provide would be greatly appreciated.

Thank you for your time and assistance!

**Comment by byroot** [comment]
Gems generally only specify a minimum ruby version, not an upper range as you can't know in advance if it will be incompatible or not.

Anyway, no incompatibilities here.
