### ISSUE TITLE
JSON dumping should support a parameter to skip nil values

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/json#590]
It's something one can easily do by calling `.compact` on the hash passed to `JSON.dump`, with the caveat of generating an extra object. Ideally one could do something of the kind:

```ruby
JSON.dump_default_options[:ignore_null] = true

JSON.dump({bang: nil}) #=> '{}'

**Comment by byroot** [comment]
Thank you for the suggestion, but I believe this is too niche of an use case to justify the extra indirection.
