### ISSUE TITLE
Installation on a machine without a compiler

### ISSUE THREAD

**Issue by mperham** [ruby/json#600]
I'm trying to install the json gem on a production machine which cannot have dev tools installed for security reasons. Would it be possible to make the native extension either optional or to publish cross platform builds for x86_64-linux (like [nokogiri does today](https://rubygems.org/gems/nokogiri))?

**Comment by byroot** [comment]
I'd have to try to pull a favor from @flavorjones, as I don't have much experience with this.

I'm also a bit on the fence because while it's very useful for gems that are hard and/or slow to compile, `json` compiles very fast, so not sure it would justify the extra complexity.

I get the "no compiler in production" use case though.

But before that, I wonder:

  - Why can't you use the version of `json` bundled with Ruby?
  - Alternatively, why can't you use `json-pure`? (I assume because it's slow but maybe not).

**Comment by mperham** [comment]
What is `json-pure`? Oh, it's `json_pure" and it is absolutely a workable solution for me. Thank you!!!

**Comment by mperham** [comment]
Ah, I just tried and unfortunately I have transitive dependencies like faraday and rubocop which pull in `json`. I don't know how to force `json_pure` -- is this possible?

**Comment by byroot** [comment]
Not really no. You'd need some bundler feature to instruct it that it's OK if `json` isn't installed. This has been a feature asked for for a very long time now.

**Comment by headius** [comment]
This ties in with the discussions about how to make gems that include a native extension but can skip building it under certain circumstances (usually for JRuby or TruffleRuby which may prefer a pure Ruby or pre built JVM extension). In this case, the json gem could have some code in extconf.rb that checks whether build tools exist, and if they don't it would warn and generate a dummy makefile that could be skipped by RG. But that's a feature that doesn't exist yet.

We have been asking for a RG or bundler feature to allow "equivalent gems" for many years but it has never gotten anywhere.

**Comment by byroot** [comment]
> In this case, the json gem could have some code in extconf.rb that checks whether build tools exist,

Yeah, I don't know if a warning would be quite enough, but we could indeed technically ship `json_pure` inside `json` and do that sort of fallback.

But as you point out, if the server doesn't even have `make` it won't work.

**Comment by byroot** [comment]
@mperham what about solution 1 ? Why the version of `json` bundled with Ruby can't satisfy bundler? Is one of your dependencies asking for a newer version than that?

**Comment by mperham** [comment]
I'm not sure. I'm installing the default Ruby for Ubuntu 24.04. Maybe it doesn't come with `json` and I need to apt-get another package?

**Comment by casperisfine** [comment]
```bash
$ podman run -it ubuntu:24
# apt-get update -y
# apt-get install -y ruby
....
# irb
irb(main):001:0> require 'json'
=> true
irb(main):002:0> JSON::VERSION
=> "2.6.3"
```

So it should work?
