### ISSUE TITLE
JSON.dump("\x82\xAC\xEF".b) no error with the C extension

### ISSUE THREAD

**Issue by eregon** [ruby/json#634]
On json 2.7.2:
```
$ ruby -rjson/ext -e 'p JSON.dump("\x82\xAC\xEF".b)'
json-2.7.2/lib/json/common.rb:306:in `generate': source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
$ ruby -rjson/pure -e 'p JSON.dump("\x82\xAC\xEF".b)'
json-2.7.2/lib/json/pure/generator.rb:453:in `encode': "\x82" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```

On json master:
```
$ ruby -rjson/ext -e 'p JSON.dump("\x82\xAC\xEF".b)'
"\"\\u0082\\u00ac\xEF\""
$ ruby -rjson/pure -e 'p JSON.dump("\x82\xAC\xEF".b)'
json-2.7.2/lib/json/pure/generator.rb:341:in `encode': "\x82" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```

**Comment by byroot** [comment]
It is known, and I don't plan to change it until 3.0.

Ref: https://github.com/ruby/json/pull/609

**Comment by eregon** [comment]
I think it's due to using `obj = rb_str_export_to_enc(obj, rb_utf8_encoding());` vs using `String#encode`, so a potential fix would be to use `String#encode` to get a `Encoding::UndefinedConversionError`.
It could also be a JSON::GeneratorError like the latest release (although inconsistent with the pure-Ruby version), that would still be better than silently accepting broken strings.

**Comment by byroot** [comment]
Hum, wait. I think I'm misreading your report.

**Comment by byroot** [comment]
yeah, this is a regression from 2.7.2, good catch I'll fix it.

**Comment by eregon** [comment]
I think it's related but not the same, https://github.com/ruby/json/pull/609 is about bytes valid in UTF-8 and this is about bytes invalid in UTF-8.

I'm not sure about the semantics of `rb_str_export_to_enc()` is it like String#encode (from `ruby -rjson/ext -e 'p JSON.dump("A".encode("UTF-32LE"))'`) but without exceptions?
What does it do if given a BINARY string with valid UTF-8 bytes?
It seems to be like `force_encoding` in that case, but unsure of the details:
`ruby -rjson/ext -e 'p JSON.dump("Aé".b)'` -> `"\"Aé\""

**Comment by byroot** [comment]
I think the function to use is `rb_str_conv_enc`

**Comment by eregon** [comment]
I guess in the C ext to preserve https://github.com/ruby/json/pull/609 we'll need something equivalent to:
```ruby
if str.encoding == BINARY
  str = str.dup.force_encoding(UTF_8)
else
  str = str.encode(UTF_8)
end
```

And then the `rb_enc_str_coderange` check after deals with the case it's not valid.

**Comment by byroot** [comment]
Yup. I got a quick patch in that effect that passes the tests: https://github.com/byroot/json/commit/170ec370e5575bf197b8939146b70c5505142018

I'll clean it up tomorrow and merge this PR with it.
