### ISSUE TITLE
Release `json_pure 2.7.3`

### ISSUE THREAD

**Issue by byroot** [ruby/json#640]
I've just cut a release of `json 2.7.3` and it should be accompanied by `json_pure 2.7.3` but I'm not an owner on rubygems.org, so I can't do it yet.

I'll do it as soon as I'm made owner by either @hsbt @nurse or @headius

**Comment by headius** [comment]
I have added you as an owner!

**Comment by byroot** [comment]
Thank you! I released `json_pure`.
