### ISSUE TITLE
json_pure: Parser Constructor Error With Ruby 3.3.5 Using Version 2.7.4

### ISSUE THREAD

**Issue by Hohlen** [ruby/json#651]
Started getting the following error after upgrading to version **2.7.4** using Ruby 3.3.5.  This error does not occur with version **2.7.2** that I rolled back to:

/Users/john/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/json_pure-2.7.4/lib/json/common.rb:222:in `initialize': _wrong number of arguments (given 2, expected 1) (ArgumentError)_

      **Parser.new(source, opts).parse**
                 ^^^^^^^^^^^^
	from /Users/john/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/json_pure-2.7.4/lib/json/common.rb:222:in `new'
	from /Users/john/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/json_pure-2.7.4/lib/json/common.rb:222:in `parse'
	from /Users/john/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/simplecov-0.22.0/lib/simplecov/last_run.rb:18:in `read'
	from /Users/john/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/simplecov-0.22.0/lib/simplecov/exit_codes/maximum_coverage_drop_check.rb:39:in `last_run'
	from /Users/john/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/simplecov-0.22.0/lib/simplecov/exit_codes/maximum_coverage_drop_check.rb:12:in `failing?'

**Comment by casperisfine** [comment]
Hum, this is weird. `simplecov` is doing a very mundane `JSON.parse` call: https://github.com/simplecov-ruby/simplecov/blob/v0.22.0/lib/simplecov/last_run.rb#L18C9-L18C48

```ruby
>> gem 'json_pure'
=> true
>> require 'json/pure'
=> true
>> JSON.parse('{}', symbolize_names: true)
=> {}
>> JSON::VERSION
=> "2.7.4"
>> JSON.parser
=> JSON::Ext::Parser
>> JSON.parser = JSON::Pure::Parser
=> JSON::Pure::Parser
>> JSON.parse('{}', symbolize_names: true)
```

Any chance you'd have a reproduction script of some sort?

Or at the very least put some debug statements in there to understand what `JSON::Parser` is, e.g. `p JSON::Parser` and `p JSON::Parser.instance_method(:initialize)`.

Because I don't see how `Parser#initialize` can possibly not accept two arguments.

**Comment by Hohlen** [comment]
Hi.  Sorry I don't have a way to easily reproduce since it's not my code (instead it's code coverage report being executed via rake).

**Comment by byroot** [comment]
Right, but this is happening on your machine, right? If you you can `bundle open simplecov` and put some debug statement or a debugger there.

**Comment by Hohlen** [comment]
Yea, I should/could. I just got home from hospital form major wrist surgery and can barely type.  The issue does not occur with version 2.7.3 if that helps.  It's definitely specific to 2.7.4.

**Comment by byroot** [comment]
No need to justified yourself, my requests do imply a "whenever you get the chance". Hope you feel better soon.

> The issue does not occur with version 2.7.3 if that helps. It's definitely specific to 2.7.4.

That does help narrow it down, thank you.

**Comment by byroot** [comment]
Ok, I think I know what's up. I bet `json_pure` is at `2.7.4`, but you also have the `json` gem at another version.

Ref: https://github.com/ruby/json/issues/650

**Comment by Hohlen** [comment]
Actually, tell me what to add to debug. I don't want to leave you hanging:
![image](https://github.com/user-attachments/assets/8c687374-5cf4-47c3-be2b-5b94e39e92d6)

overage report generated for Functional Tests, Unit Tests to /Users/john/git/fantasy-golf/coverage.
Line Coverage: 65.96% (5208 / 7896)
debug JSON.parse(...)
{"result":{"line":65.95}}
/Users/john/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/json_pure-2.7.4/lib/json/common.rb:222:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)

      Parser.new(source, opts).parse
                 ^^^^^^^^^^^^

**Comment by Hohlen** [comment]
I don't have the json gem specified, actually.  Is that what I need to do?

```
    csv (3.3.0)
    date (3.3.4)
    docile (1.4.1)
    ed25519 (1.3.0)
    fiddle (1.1.4)
    i18n (1.14.6)
      concurrent-ruby (~> 1.0)
    jmespath (1.6.2)
    json_pure (2.7.4)
    logger (1.6.1)
    metaclass (0.0.4)
```

**Comment by byroot** [comment]
No need, I found a repro:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'json_pure', "2.7.4"
  gem 'json', "~> 2.6.0"
end

require 'json/ext'
require 'json/pure'
JSON.parser = JSON::Ext::Parser
JSON.parse('{}', symbolize_names: true)
```

```
$ ruby foo.rb
JSON::Pure::Parser
/Users/byroot/.gem/rubies/3.3.4/gems/json_pure-2.7.4/lib/json/common.rb:222:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)

      Parser.new(source, opts).parse
                 ^^^^^^^^^^^^
	from /Users/byroot/.gem/rubies/3.3.4/gems/json_pure-2.7.4/lib/json/common.rb:222:in `new'
	from /Users/byroot/.gem/rubies/3.3.4/gems/json_pure-2.7.4/lib/json/common.rb:222:in `parse'
	from foo.rb:13:in `<main>'

```

You can rest your wrist :)

> I don't have the json gem specified, actually.

It probably is the stdlib version, I'll try to adjust my repro.

**Comment by byroot** [comment]
Yep, even simpler:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'json_pure', "2.7.4"
end

require 'json'
JSON.parse('{}', symbolize_names: true)
```

**Comment by Hohlen** [comment]
Nice.  You nailed it! 
Do I need to add a gem or does this require a code fix to the json_pure lib?

**Comment by byroot** [comment]
Yeah, I'll have to cut a `json_pure 2.7.5`, in the meantime you can lock it to `2.7.3`. 

Thank you very much for the bug report.

**Comment by Hohlen** [comment]
> Yeah, I'll have to cut a `json_pure 2.7.5`, in the meantime you can lock it to `2.7.3`.
> 
> Thank you very much for the bug report.

Thank you for the quick fix!
