### ISSUE TITLE
NoMethodError:   undefined method `load_file' for JSON:Module

### ISSUE THREAD

**Issue by jterapin** [ruby/json#696]
Hello! AWS SDK for Ruby's CI w/ Ruby 2.x environment is encountering the following error when using the most recent gem:
```
NoMethodError:
  undefined method `load_file' for JSON:Module
```
While I understand the Ruby version requirement has recently been bumped to 2.7 based on the [changelog](https://github.com/ruby/json/blob/master/CHANGES.md?plain=1#L12). The above error is still encountered for Ruby 2.7.

Pinning the json gem to `2.7.5` for Ruby 2.x versions solves the issue. 
Please let me know if this is expected behavior for Ruby 2.7 - thanks!

Edit - example CI failure: https://github.com/aws/aws-sdk-ruby/actions/runs/11708650797/job/32611314507

**Comment by byroot** [comment]
I think I see. Ruby 2.7 ships with `json 2.30` as a standard gem, which means if you don't specify a version requirement, that's what you'll get, and that version doesn't have `.load_file`.

`load_file` was added in `2.4.0` so you probably want to set a dependency on that.

**Comment by jterapin** [comment]
Thanks for the quick response!

**Comment by byroot** [comment]
Opened a downstream PR at https://github.com/aws/aws-sdk-ruby/pull/3140

**Comment by mullermp** [comment]
>Ruby 2.7 ships with json 2.3,0 as a standard gem, which means if you don't specify a version requirement, that's what you'll get, and that version doesn't have .load_file.

If this is true, how was this working before?

**Comment by byroot** [comment]
I don't know for sure, but I suspect the logic of bundler is to lookup the latest version, see it it can't install it on that Ruby version and fallback to the stdlib?

Also I assume the bundler that is shipped with these old Ruby is old too, so it may or may not still be the behavior today?

**Comment by mullermp** [comment]
I see, ok. For normal gems, if you declare a ruby version requirement on the gemspec, we would download the most recent version that supports the ruby version constraint. Since you've bumped a new version that is > 2.7, I think that reasoning makes sense, it would have to default to stdlib.

**Comment by byroot** [comment]
I think the big difference with other gems, is that on your CI at least, you don't already have them around when you bundle.

Bundler tend to favor using whatever versions of gems that already exist locally is they satisfy the requirement.

You can test this with the follwing script:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'json'
end

puts JSON::VERSION
```

And you can run `gem uninstall json` to cleanup, and then install whichever version with `gem install -v X.Y.Z`, and you'l see bundler will use the newest available locally before looking for new versions on `rubygems`.
