### ISSUE TITLE
Encoding::InvalidByteSequenceError with json 2.8.1

### ISSUE THREAD

**Issue by jterapin** [ruby/json#697]
Hi again! 

When using json 2.8.1 with Ruby 3.2.0 (for additional context, we use CodeBuild instances)  - been running into the following error:
```
Encoding::InvalidByteSequenceError: "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError)
/codebuild/output/src3972890485/src/.gems/ruby/3.2.0/gems/json-2.8.1/lib/json/common.rb:204:in `encode'
/codebuild/output/src3972890485/src/.gems/ruby/3.2.0/gems/json-2.8.1/lib/json/common.rb:204:in `parse'
/codebuild/output/src3972890485/src/.gems/ruby/3.2.0/gems/json-2.8.1/lib/json/common.rb:204:in `parse'
/codebuild/output/src3972890485/src/.gems/ruby/3.2.0/gems/json-2.8.1/lib/json/common.rb:710:in `load'
/codebuild/output/src3972890485/src/aws-sdk-ruby/build_tools/services.rb:93:in `load_docs'
```

The `load_docs` referred above is here: https://github.com/aws/aws-sdk-ruby/blob/version-3/build_tools/services.rb#L93
Could any of the recent changes have effected this? Reverting back to json 2.7.6 has fixed this for us.

`InvalidByteSequenceError: "\xE2" on US-ASCII` feels like its trying to read it as ASCII instead of UTF-8. 

Any guidance will be appreciated. Thanks much!!!

**Comment by byroot** [comment]
Yes, I'm making the library progressively stricter about encoding, this one I think I should just note in the CHANGELOG.

> InvalidByteSequenceError: "\xE2" on US-ASCII 

This means you are passing an UTF-8 strings, but it's encoded as ASCII, looking at your code, it comes directly from `File.read`, so somehow you must have `Encoding.default_external == Encoding::ASCII`.

```bash
ruby -e 'Encoding.default_external = Encoding::ASCII; p File.read("/etc/passwd").encoding'
#<Encoding:US-ASCII>
```

I think you should check your `$LANG` environment variable. But yes, either way you are passing an invalid string to JSON so it's expected it raises. We only have a small exception for binary strings but that's it.

**Comment by byroot** [comment]
A quick workaround can also be:

```ruby
JSON.load(File.read(model_path('docs-2.json', models_dir), encoding: Encoding::UTF_8))
```

**Comment by jterapin** [comment]
Hi! Just wondering on the ETA on the gem update with this fix? TIA

**Comment by byroot** [comment]
I'm just waiting a few days to see if some other issues are reported.

**Comment by byroot** [comment]
2.8.2 was released.

**Comment by jterapin** [comment]
Hello @byroot - it's me again. We used the latest version of the `json` gem and still encountered the same error in our CodeBuild project (see below). I may have to make some configuration on the CodeBuild project settings (based on reading this [post](https://austincloud.guru/2018/03/13/codebuild-and-utf-8/) but before I look into doing that - I wanted to double check with you. Thanks again. 

```
/codebuild/output/src2789127840/src/aws-sdk-ruby/build_tools/services.rb:188: warning: previous definition of Services was here
rake aborted!
Encoding::InvalidByteSequenceError: "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError)
/codebuild/output/src2789127840/src/.gems/ruby/3.2.0/gems/json-2.8.2/lib/json/common.rb:205:in `encode'
/codebuild/output/src2789127840/src/.gems/ruby/3.2.0/gems/json-2.8.2/lib/json/common.rb:205:in `parse'
/codebuild/output/src2789127840/src/.gems/ruby/3.2.0/gems/json-2.8.2/lib/json/common.rb:205:in `parse'
/codebuild/output/src2789127840/src/.gems/ruby/3.2.0/gems/json-2.8.2/lib/json/common.rb:711:in `load'
/codebuild/output/src2789127840/src/aws-sdk-ruby/build_tools/services.rb:93:in `load_docs'
/codebuild/output/src2789127840/src/aws-sdk-ruby/build_tools/services.rb:70:in `build_service'
/codebuild/output/src2789127840/src/aws-sdk-ruby/build_tools/services.rb:51:in `block in services'
/codebuild/output/src2789127840/src/aws-sdk-ruby/build_tools/services.rb:50:in `each'
/codebuild/output/src2789127840/src/aws-sdk-ruby/build_tools/services.rb:50:in `inject'
/codebuild/output/src2789127840/src/aws-sdk-ruby/build_tools/services.rb:50:in `services'
/codebuild/output/src2789127840/src/aws-sdk-ruby/build_tools/services.rb:42:in `each'
/codebuild/output/src2789127840/src/aws-sdk-ruby/tasks/build.rake:7:in `block in <top (required)>'
tasks/sdk.rake:60:in `block in <top (required)>'
/codebuild/output/src2789127840/src/releaseTools/lib/rake_code_build_output.rb:8:in `top_level'
/codebuild/output/src2789127840/src/.gems/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Tasks: TOP => build
(See full trace by running task with --trace)
```

**Comment by byroot** [comment]
The backtrace clearly shows you are not using `.load_file`.

**Comment by jterapin** [comment]
Aaaah, thanks for catching that.

**Comment by jterapin** [comment]
Hello from the AWS SDK for Ruby. Hope you are well, @byroot ~

We have a customer who is using the `json` gem with Ruby 3.4 (within Ruby lambda environment) and running into a similar issue (same error). Further context: https://github.com/aws/aws-sdk-ruby/issues/3231

I was able to reproduce the same error:
``` 
/var/lang/lib/ruby/3.4.0/json/common.rb:221:in 'String#encode': "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError)
	from /var/lang/lib/ruby/3.4.0/json/common.rb:221:in 'JSON::Ext::Parser.parse'
	from /var/lang/lib/ruby/3.4.0/json/common.rb:221:in 'JSON.parse'
	from /var/lang/lib/ruby/gems/3.4.0/gems/aws-sdk-core-3.222.1/lib/aws-sdk-core/json/json_engine.rb:10:in 'Aws::Json::JsonEngine.load'
	from /var/lang/lib/ruby/gems/3.4.0/gems/aws-sdk-core-3.222.1/lib/aws-sdk-core/json.rb:43:in 'Aws::Json.load'
```
Here's where we use `JSON.parse` within the SDK: https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/aws-sdk-core/json/json_engine.rb#L10

Thoughts? Thanks in advance!

**Comment by byroot** [comment]
You customer is passing you an invalid string. It's marked as being ASCII, but contains UTF-8.

Can't tell you any more than that.

**Comment by byroot** [comment]
> I would like to know the reason that we don’t get the deprecation warning is that it’s for ASCII-8BIT, not ASCII, right?

Yes, mostly likely. But it's really a huge corner case. `ASCII-8BIT (BINARY)` is common, because it's kind of a fallback. But to have an `US-ASCII` string with chinese characters in it, some code likely went out of its way to get there.
