### ISSUE TITLE
Better error debugging for generation

### ISSUE THREAD

**Issue by mperham** [ruby/json#710]
I'm trying to figure out why JSON is blowing up when generating the JSON for a big ole Hash of stuff. It raises a GeneratorError, but with no context so I can't easily tell where my bad data is. The line in question is here:

https://github.com/ruby/json/blob/55015fa91eb48a12bebe33869b7048b3e9818154/ext/json/ext/generator/generator.c#L912

I would suggest this error include the relevant object at fault. Something like:

```ruby
class JSON::GeneratorError
  attr_reader :invalid_element
end
```

**Comment by byroot** [comment]
Makes sense. Wouldn't be too hard to implement.

**Comment by mperham** [comment]
Thank you, it worked great.

Should it emit the invalid object as part of `message`? That's extremely useful context that most people won't know exists. Is the attribute in the RDoc?

**Comment by byroot** [comment]
The object may be huge, that's why it's included in `detailed_message` and not just `message`, to avoid things like: https://bugs.ruby-lang.org/issues/18285

**Comment by mperham** [comment]
TIL about `#detailed_message`! I think I could roll this into Sidekiq's debugging output: turn on debugging => get detailed_message logged which will solve my need.

https://docs.ruby-lang.org/en/master/Exception.html#method-i-detailed_message
