### ISSUE TITLE
Document using IO objects / compression

### ISSUE THREAD

**Issue by mperham** [ruby/json#711]
I'd like to generate a large blob of JSON and I also want to compress it at the same time. Right now I can do this:

```ruby
json = JSON.generate(data)
result = Zlib.gzip(json)
```

Is it possible to avoid this intermediate variable and pass in a gzip IO so generation streams right into compression? Would it be reasonable to build in easy/efficient gzip integration, e.g. for streaming API/JSON responses with `Content-Encoding: gzip`?

**Comment by byroot** [comment]
It's documented here: https://docs.ruby-lang.org/en/master/JSON.html#method-i-dump

The dump method accepts an IO and if given writes into it.

You can combine that with `GZipWriter` to do what you want: https://docs.ruby-lang.org/en/master/Zlib/GzipWriter.html

One thing to note though is that until https://github.com/ruby/json/pull/686 (not yet released) the entire JSON would be generated before starting to write in the IO, after that change it write in 16kIB chunks.
