### ISSUE TITLE
json.pretty_generate behaviour changed in 2.8.0

### ISSUE THREAD

**Issue by YOU54F** [ruby/json#714]
Issue: Empty hashes no longer print over two lines in json 2.8.0 when using `JSON.pretty_generate`

Expected: Empty hashes would print over two lines in json 2.8.0
Actual: Empty hashes would print on a single line in json 2.8.0

Observations: Only occurs in Ruby 3.0.x +, works correctly in 2.7

## Reproducer

Change the gem version, and run script

```rb
# !/usr/bin/env ruby
if __FILE__ == $0

  require 'bundler/inline'

  gemfile(true) do
    source 'https://rubygems.org'

    gem 'json', '2.8.0'
    # gem 'json', '2.7.6'
  end

  expected_data_1 = {
    "thing": {
      "alligator": {
        "name": "Mary"
      }
    }
  }
  data_1 = { thing: { alligator: { name: 'Mary' } } }
  prettified_data_1 = JSON.pretty_generate(data_1)
  puts prettified_data_1


  data_2 = { thing: {} }
  prettified_data_2 = JSON.pretty_generate(data_2)
  puts prettified_data_2
end
```

## Output

With Ruby 3.x

2.7.6
```json
{
  "thing": {
    "alligator": {
      "name": "Mary"
    }
  }
}
{
  "thing": {
  }
}
```

2.8.0

```json
{
  "thing": {
    "alligator": {
      "name": "Mary"
    }
  }
}
{
  "thing": {}
}
```

**Comment by YOU54F** [comment]
this was change was originally requested to be optional and opt in.

https://github.com/ruby/json/issues/437

however it was implemented as the default with no way of preserving the existing behaviour 

https://github.com/ruby/json/pull/626

also not noted as a breaking change in the release notes.

**Comment by byroot** [comment]
Yes this change was fully intended I just forgot to include it in the changelog, sorry.

I don't really want to add an option for it as the new output is much more readable and there's already a tons of conditionals that hurt performance on this codepath.

Why is this change a problem for you?

**Comment by YOU54F** [comment]
thats okay sometimes things slip through the net.

its changed the output of our diffs for a project - see description in the following PR, which for us anyway isn’t correct.

https://github.com/pact-foundation/pact-support/pull/111

**Comment by byroot** [comment]
Seems like you have a good workaround to make your test suite work with both versions.

**Comment by byroot** [comment]
> I wasn’t sure if it was the right approach

Depends what you are trying to assert exactly. If the exact formatting doesn't matter, you can also compare `JSON.parse` results.
