### ISSUE TITLE
TypeError when calling Fixnum#to_son 

### ISSUE THREAD

**Issue by ifesdjeen** [ruby/json#77]
How to reproduce:
ruby-1.9.2-p136 :001 > 1.to_json
TypeError: wrong argument type JSON::Pure::Generator::State (expected Data)

How to fix:

```
class Fixnum
  def to_json(options = nil)
    to_s
  end
end
```

Issue might be a bit more fundamental. Do you have any hints?

BTW, i'm not the only one facing it:
http://prettystatemachine.blogspot.com/2010/09/typeerrors-in-tojson-make-me-briefly.html
http://blog.ethanvizitei.com/2010/11/json-pure-ruins-my-morning.html

**Comment by byroot** [comment]
Pretty sure this is no longer a bug.
